### ISSUE TITLE
Main.py uses Absolute Path

### ISSUE THREAD

**Issue by ReeseHatfield** [IgorLytkin/Wireshark2Neo4j#1]
Main.py uses an absolute path, which does not work on my machine.

Main.py использует абсолютный путь, который не работает на моей машине.

**Comment by IgorLytkin** [comment]
Спасибо за комментарий. Добавил загрузку параметров из файла .env, пример файла параметров.
Thanks for the comment. Added parameter loading from the .env file, an example of a parameter file.
